version: '3.9'

services:
  # PostgreSQL Database for local development
  postgres:
    image: postgres:16-bookworm
    container_name: relayforge-postgres-local
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: relayforge_local
    volumes:
      - postgres_local_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d relayforge_local"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis for local development (optional)
  redis:
    image: redis:7-bookworm
    container_name: relayforge-redis-local
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_local_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_local_data:
  redis_local_data: